# Generated by Django 5.2.18 on 2026-10-10 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("business", "Business Financial Model"),
                            ("startup", "Startup Financial Model"),
                            ("real_estate", "Real Estate Financial Model"),
                            ("investment", "Investment Financial Model"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("NGN", "NGN · Nigerian naira (₦)"),
                            ("USD", "USD · US dollar ($)"),
                            ("GBP", "GBP · British pound sterling (£)"),
                        ],
                        default="NGN",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("calculated", "Calculated")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("inputs", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_calculated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-updated_at"],
                        name="projects_pr_owner_i_242348_idx",
                    )
                ],
            },
        ),
    ]
