"""whatsapp notification preferences

Revision ID: 1889870066a0
Revises: c244e77c88be
Create Date: 2026-10-05 23:27:06.755998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1889870066a0'
down_revision: Union[str, None] = 'c244e77c88be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_announcements', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('whatsapp_events', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_events')
        batch_op.drop_column('whatsapp_announcements')

    # ### end Alembic commands ###
