"""content pack: sources, legislation, elections

Revision ID: c244e77c88be
Revises: 9a9061abd072
Create Date: 2026-10-04 12:14:10.506727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c244e77c88be'
down_revision: Union[str, None] = '9a9061abd072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('constituency', sa.String(length=160), nullable=False),
    sa.Column('candidate', sa.String(length=160), nullable=False),
    sa.Column('party', sa.String(length=40), nullable=False),
    sa.Column('outcome', sa.String(length=300), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('votes_note', sa.String(length=300), nullable=True),
    sa.Column('election_date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verification_note', sa.String(length=500), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('election_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_election_records_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_election_records_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_election_records_year'), ['year'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('accessed_date', sa.Date(), nullable=True),
    sa.Column('reliability_level', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('content_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_type', 'content_id', 'source_id', name='uq_content_source')
    )
    with op.batch_alter_table('content_sources', schema=None) as batch_op:
        batch_op.create_index('ix_content_sources_item', ['content_type', 'content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_sources_source_id'), ['source_id'], unique=False)

    op.create_table('legislative_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('bill_number', sa.String(length=40), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('sponsor', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('legislative_stage', sa.String(length=30), nullable=False),
    sa.Column('official_status', sa.String(length=300), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verification_note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legislative_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legislative_records_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_legislative_records_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legislative_records_legislative_stage'), ['legislative_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_legislative_records_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_legislative_records_verification_status'), ['verification_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_legislative_records_year'), ['year'], unique=False)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_news_verification_status'), ['verification_status'], unique=False)

    with op.batch_alter_table('principal_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_caption', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('photo_source_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('photo_source_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('photo_usage', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('photo_rights_status', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('badges', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('facts', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('metrics', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('metrics_note', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('metrics_source_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('project_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_project_sources_source_id'), ['source_id'], unique=False)
        batch_op.create_foreign_key('fk_project_sources_source_id', 'sources', ['source_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_status', sa.String(length=30), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('status_note', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('category_label', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('reported_cost', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('reported_length', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_projects_project_status'), ['project_status'], unique=False)

    # ### end Alembic commands ###

    # Verification now distinguishes Verified / Reported / Self-reported / Pending.
    # Earlier "unverified" and "pending review" records are pending verification.
    op.execute(
        "UPDATE projects SET verification_status = 'pending' "
        "WHERE verification_status IN ('unverified', 'pending_review')"
    )


def downgrade() -> None:
    op.execute("UPDATE projects SET verification_status = 'unverified' WHERE verification_status = 'pending'")
    op.execute(
        "UPDATE projects SET verification_status = 'pending_review' "
        "WHERE verification_status IN ('reported', 'self_reported')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_project_status'))
        batch_op.drop_column('last_verified_at')
        batch_op.drop_column('reported_length')
        batch_op.drop_column('reported_cost')
        batch_op.drop_column('category_label')
        batch_op.drop_column('status_note')
        batch_op.drop_column('project_status')

    with op.batch_alter_table('project_sources', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_sources_source_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_project_sources_source_id'))
        batch_op.drop_column('source_id')

    with op.batch_alter_table('principal_profile', schema=None) as batch_op:
        batch_op.drop_column('metrics_source_url')
        batch_op.drop_column('metrics_note')
        batch_op.drop_column('metrics')
        batch_op.drop_column('facts')
        batch_op.drop_column('badges')
        batch_op.drop_column('photo_rights_status')
        batch_op.drop_column('photo_usage')
        batch_op.drop_column('photo_source_url')
        batch_op.drop_column('photo_source_name')
        batch_op.drop_column('photo_caption')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_verification_status'))
        batch_op.drop_column('verification_status')

    with op.batch_alter_table('legislative_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legislative_records_year'))
        batch_op.drop_index(batch_op.f('ix_legislative_records_verification_status'))
        batch_op.drop_index(batch_op.f('ix_legislative_records_slug'))
        batch_op.drop_index(batch_op.f('ix_legislative_records_legislative_stage'))
        batch_op.drop_index(batch_op.f('ix_legislative_records_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_legislative_records_category'))

    op.drop_table('legislative_records')
    with op.batch_alter_table('content_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_sources_source_id'))
        batch_op.drop_index('ix_content_sources_item')

    op.drop_table('content_sources')
    op.drop_table('sources')
    with op.batch_alter_table('election_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_election_records_year'))
        batch_op.drop_index(batch_op.f('ix_election_records_slug'))
        batch_op.drop_index(batch_op.f('ix_election_records_deleted_at'))

    op.drop_table('election_records')
    # ### end Alembic commands ###
